# Generated by Django 6.1.1 on 2026-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_authority',
            field=models.CharField(blank=True, max_length=100, verbose_name='Authority زرین پال'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری پرداخت'),
        ),
    ]
